### ISSUE TITLE
Runtime error when running in lite mode with proxyProtocol and backend server with only ipv6

### ISSUE THREAD

**Issue by enchantstudio** [minekube/gate#133]
Gate is a very good software, this idea is ready for the cloud!

Detail: Support IPV6 address listening and forward.

ERROR MESSAGE:

panic: runtime error: invalid memory address or nil pointer dereference

```
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.19.4/x64/src/runtime/debug/stack.go:24 +0x65
golang.org/x/sync/singleflight.newPanicError({0xc63cc0?, 0x1436d10})
	/home/runner/go/pkg/mod/golang.org/x/sync@v0.1.0/singleflight/singleflight.go:35 +0x2c
golang.org/x/sync/singleflight.(*Group).doCall.func2.1()
	/home/runner/go/pkg/mod/golang.org/x/sync@v0.1.0/singleflight/singleflight.go:184 +0x3b
panic({0xc63cc0, 0x1436d10})
	/opt/hostedtoolcache/go/1.19.4/x64/src/runtime/panic.go:884 +0x212
go.minekube.com/gate/pkg/edition/java/lite.dialRoute.func1()
	/home/runner/work/gate/gate/pkg/edition/java/lite/forward.go:148 +0x29
go.minekube.com/gate/pkg/edition/java/lite.dialRoute({0xeb9410?, 0xc000112000?}, 0x10?, {0xeb40f8, 0xc0000b82d0}, 0xc00010f580, {0xc000270b90, 0x9}, 0xc0000b84e0, 0xc0000ce280, ...)
	/home/runner/work/gate/gate/pkg/edition/java/lite/forward.go:161 +0x2fd
go.minekube.com/gate/pkg/edition/java/lite.ResolveStatusResponse.func1({0xeb9410, 0xc000112000})
	/home/runner/work/gate/gate/pkg/edition/java/lite/forward.go:256 +0x1b6
go.minekube.com/gate/pkg/edition/java/lite.ResolveStatusResponse.func2(0x203000?, {0x203000?, 0xc0000be680?})
	/home/runner/work/gate/gate/pkg/edition/java/lite/forward.go:273 +0x50
github.com/jellydator/ttlcache/v3.LoaderFunc[...].Load(0x203000?, 0xc0000b8810?, {0xc000270b90?, 0xc000063580?})
	/home/runner/go/pkg/mod/github.com/jellydator/ttlcache/v3@v3.0.1/cache.go:535 +0x2b
github.com/jellydator/ttlcache/v3.(*SuppressedLoader[...]).Load.func1()
	/home/runner/go/pkg/mod/github.com/jellydator/ttlcache/v3@v3.0.1/cache.go:575 +0x3a
golang.org/x/sync/singleflight.(*Group).doCall.func2(0xc0000f9dae, 0xc0000ac230, 0x1?)
	/home/runner/go/pkg/mod/golang.org/x/sync@v0.1.0/singleflight/singleflight.go:189 +0x6f
golang.org/x/sync/singleflight.(*Group).doCall(0xc5b960?, 0xc0000b8810?, {0xc0000d61c0?, 0x9?}, 0x40b287?)
	/home/runner/go/pkg/mod/golang.org/x/sync@v0.1.0/singleflight/singleflight.go:191 +0xa5
golang.org/x/sync/singleflight.(*Group).Do(0xc0000a6390, {0xc0000d61c0, 0x9}, 0x0?)
	/home/runner/go/pkg/mod/golang.org/x/sync@v0.1.0/singleflight/singleflight.go:104 +0x165
github.com/jellydator/ttlcache/v3.(*SuppressedLoader[...]).Load(0xc0000c2108, 0xc000172800, {0xc000270b90, 0x9})
	/home/runner/go/pkg/mod/github.com/jellydator/ttlcache/v3@v3.0.1/cache.go:574 +0xe5
github.com/jellydator/ttlcache/v3.(*Cache[...]).Get(0xc000172800, {0xc000270b90, 0x9}, {0xc0000637c0, 0x1, 0xc0000637d0})
	/home/runner/go/pkg/mod/github.com/jellydator/ttlcache/v3@v3.0.1/cache.go:270 +0x255
go.minekube.com/gate/pkg/edition/java/lite.ResolveStatusResponse.func3()
	/home/runner/work/gate/gate/pkg/edition/java/lite/forward.go:284 +0x65
created by go.minekube.com/gate/pkg/edition/java/lite.ResolveStatusResponse
	/home/runner/work/gate/gate/pkg/edition/java/lite/forward.go:284 +0x4ef


goroutine 22 [running]:
golang.org/x/sync/singleflight.(*Group).doCall.func1()
	/home/runner/go/pkg/mod/golang.org/x/sync@v0.1.0/singleflight/singleflight.go:161 +0x2d3
golang.org/x/sync/singleflight.(*Group).doCall(0xc5b960?, 0xc0000b8810?, {0xc0000d61c0?, 0x9?}, 0x40b287?)
	/home/runner/go/pkg/mod/golang.org/x/sync@v0.1.0/singleflight/singleflight.go:196 +0xc2
golang.org/x/sync/singleflight.(*Group).Do(0xc0000a6390, {0xc0000d61c0, 0x9}, 0x0?)
	/home/runner/go/pkg/mod/golang.org/x/sync@v0.1.0/singleflight/singleflight.go:104 +0x165
github.com/jellydator/ttlcache/v3.(*SuppressedLoader[...]).Load(0xc0000c2108, 0xc000172800, {0xc000270b90, 0x9})
	/home/runner/go/pkg/mod/github.com/jellydator/ttlcache/v3@v3.0.1/cache.go:574 +0xe5
github.com/jellydator/ttlcache/v3.(*Cache[...]).Get(0xc000172800, {0xc000270b90, 0x9}, {0xc0000637c0, 0x1, 0xc0000637d0})
	/home/runner/go/pkg/mod/github.com/jellydator/ttlcache/v3@v3.0.1/cache.go:270 +0x255
go.minekube.com/gate/pkg/edition/java/lite.ResolveStatusResponse.func3()
	/home/runner/work/gate/gate/pkg/edition/java/lite/forward.go:284 +0x65
created by go.minekube.com/gate/pkg/edition/java/lite.ResolveStatusResponse
	/home/runner/work/gate/gate/pkg/edition/java/lite/forward.go:284 +0x4ef

```

**Comment by robinbraemer** [comment]
Could you please provide the config and setup you are trying to archive? Do all servers have an ipv6?

**Comment by enchantstudio** [comment]
Yes, this is my config.

```
config:
  bind: 0.0.0.0:5998
  lite:
    enabled: true
    routes:
      - host: '*.playl.net'
        backend: test:5000
        pingCacheTTL: 5s
        proxyProtocol: true
```

In this config, I used '/etc/hosts' to set the test host, it's a IPV6 address.
I'm sure I've set up the right backend server and it's ready to be connected.

**Comment by enchantstudio** [comment]
Yes, it's my config file.
```
config:
  bind: 0.0.0.0:5998
  lite:
    enabled: true
    routes:
      - host: THIS_IS_MY_DOMAIN
        backend: test:5000
        pingCacheTTL: 5s
        proxyProtocol: true
```

In this config, I used `/etc/hosts` file to redirect test to my IPv6 backend server.
I'm sure I've set up the right backend server and it's ready to be connected.

**Comment by enchantstudio** [comment]
And all server have ipv6 address

**Comment by Dmitri233** [comment]
Gate does lack some support for IPv6.
For example if you try to listen only on Ipv6
```
config:
   bind: [::]:25565
```
Connect to server using link-local ipv6
```
  servers:
    server1: [fe80::a8bb:ccff:feda:cf52]:25577
```
will report a configuration file error

But if you use a domain name, and the domain name only has aaaa (ipv6) records, and not use `proxy-protocol=true`
The following errors are reported:
```
2023-01-12T19:25:54.427+0800    INFO    java.client.player      proxy/switch.go:174     unable to connect to server     {"name": "x", "id": "x", "serverName": "server1", "serverAddr": "test:25577", "error": "error connecting to backend server \"server1\": dial tcp [fe80::a8bb:ccff:feda:cf52]:25577: connect: invalid argument"}

2023-01-12T19:25:54.427+0800    INFO    java.client.player      proxy/player.go:599     Player has been disconnected    {"name": "x", "id": "x", "reason": "§cUnable to connect to \"server1\". Try again later."}
```

**Comment by robinbraemer** [comment]
I think this is a configuration error. Gate is tested to work with dual stack IP and you definitely don't need `/etc/hosts`. :)

If you want to configure IPv6 you need to `"quote"` the config value to parse the YAML correctly:
```yaml
config:
  bind: '[::]:25565'
  servers:
    server1: '[::]:25566'
  try:
    - server1
```

- `[::]` compares to `0.0.0.0`
- `[::1]` compares to `localhost`

**Comment by Dmitri233** [comment]
Yes, `"quote"` needs to be added. After that the gate works fine in normal mode.
Once the lite mode is used and `proxyProtocol: true` is enabled, the error mentioned at the beginning of issuse will appear

and Minecraft client(1.19.3) If you use a domain name with only aaaa records, the client can connect, if you have both a and aaaa records, the client will always give priority to ipv4

**Comment by enchantstudio** [comment]
This problem seems to occur only in Lite mode, when the backend server uses IPv6 addresses and proxyProtocol is enabled
Proxy behind proxy for ipv6 in lite mode

**Comment by enchantstudio** [comment]
Probably due to `TCPv4` in file `/pkg/edition/java/lite/forward.go` at line 156

**Comment by robinbraemer** [comment]
Nice finding friends! 
Will use the `proxyproto.HeaderProxyFromAddrs` helper method here :)

**Comment by enchantstudio** [comment]
It's good to see you commenting on our code, but unfortunately, your part of the code is not able to solve the problem, and after our testing, it still reports the same error as described at the beginning of this issue.
