### ISSUE TITLE
Runtime error when running in lite mode

### ISSUE THREAD

**Issue by YTiceice** [minekube/gate#278]
I found that it would crash from time to time, causing all my players to be disconnected.
```
panic: runtime error: invalid memory address or nil pointer dereference                                                                                                                  [1214/1936]                                                                                                                                                                                                    
runtime/debug.Stack()                                                                                                                                                                               
        /opt/hostedtoolcache/go/1.21.5/x64/src/runtime/debug/stack.go:24 +0x5e                                                                                                                      
golang.org/x/sync/singleflight.newPanicError({0xb366e0?, 0x1253970})                                                                                                                                
        /home/runner/go/pkg/mod/golang.org/x/sync@v0.5.0/singleflight/singleflight.go:44 +0x26                                                                                                      
golang.org/x/sync/singleflight.(*Group).doCall.func2.1()                                                                                                                                            
        /home/runner/go/pkg/mod/golang.org/x/sync@v0.5.0/singleflight/singleflight.go:193 +0x34                                                                                                     
panic({0xb366e0?, 0x1253970?})                                                                                                                                                                      
        /opt/hostedtoolcache/go/1.21.5/x64/src/runtime/panic.go:914 +0x21f                                                                                                                          
go.minekube.com/gate/pkg/edition/java/lite.dialRoute.func1()                                                                                                                                        
        /home/runner/work/gate/gate/pkg/edition/java/lite/forward.go:210 +0x23                                                                                                                      
go.minekube.com/gate/pkg/edition/java/lite.dialRoute({0xd348d8?, 0xc0015006c0?}, 0xbe80c0?, {0xd31f58?, 0xc00252f890}, 0xc000f96c18, {0xc001890a98, 0x13}, 0xc00252fb00, 0xc000b08f00, ...)         
        /home/runner/work/gate/gate/pkg/edition/java/lite/forward.go:241 +0x55e                                                                                                                     
go.minekube.com/gate/pkg/edition/java/lite.resolveStatusResponse.func1({0xd346a8, 0x129de80})                                                                                                       
        /home/runner/work/gate/gate/pkg/edition/java/lite/forward.go:360 +0x1ee                                                                                                                     
go.minekube.com/gate/pkg/edition/java/lite.resolveStatusResponse.func2({{0x1800?, 0x1800?}, 0xb707a0?})                                                                                             
        /home/runner/work/gate/gate/pkg/edition/java/lite/forward.go:376 +0x29                                                                                                                      
go.minekube.com/gate/pkg/edition/java/lite.resolveStatusResponse.withLoader[...].func4({{0xc001890a98?, 0x0?}, 0xc000000076?})                                                                      
        /home/runner/work/gate/gate/pkg/edition/java/lite/forward.go:426 +0x52                                                                                                                      
github.com/jellydator/ttlcache/v3.LoaderFunc[...].Load(...)                                                                                                                                         
        /home/runner/go/pkg/mod/github.com/jellydator/ttlcache/v3@v3.1.1/cache.go:664                                                                                                               
github.com/jellydator/ttlcache/v3.(*SuppressedLoader[...]).Load.func1()                                                                                                                             
        /home/runner/go/pkg/mod/github.com/jellydator/ttlcache/v3@v3.1.1/cache.go:704 +0x39                                                                                                         
golang.org/x/sync/singleflight.(*Group).doCall.func2(0xc00204dd96, 0xc0017964b0, 0x7f2ff12c8948?)                                                                                                   
        /home/runner/go/pkg/mod/golang.org/x/sync@v0.5.0/singleflight/singleflight.go:198 +0x64                                                                                                     
golang.org/x/sync/singleflight.(*Group).doCall(0xb33880?, 0xc0000fb590?, {0xc00291e1c0?, 0x19?}, 0xc0026dc180?)
        /home/runner/go/pkg/mod/golang.org/x/sync@v0.5.0/singleflight/singleflight.go:200 +0x96
golang.org/x/sync/singleflight.(*Group).Do(0xc00010faa0, {0xc00291e1c0, 0x19}, 0xc0003e26b8?)
        /home/runner/go/pkg/mod/golang.org/x/sync@v0.5.0/singleflight/singleflight.go:113 +0x15a
github.com/jellydator/ttlcache/v3.(*SuppressedLoader[...]).Load(0xd35e60, 0xc000142c00, {{0xc001890a98, 0x13}, 0x2fb})
        /home/runner/go/pkg/mod/github.com/jellydator/ttlcache/v3@v3.1.1/cache.go:703 +0x111
github.com/jellydator/ttlcache/v3.(*Cache[...]).getWithOpts(0xd44620, {{0xc001890a98, 0x100000001?}, 0xc000aa3140?}, 0x1?, {0xc0003e27c0, 0x1, 0xc0003e27d0})
        /home/runner/go/pkg/mod/github.com/jellydator/ttlcache/v3@v3.1.1/cache.go:229 +0x236
github.com/jellydator/ttlcache/v3.(*Cache[...]).Get(...)
        /home/runner/go/pkg/mod/github.com/jellydator/ttlcache/v3@v3.1.1/cache.go:321
go.minekube.com/gate/pkg/edition/java/lite.resolveStatusResponse.func3()
        /home/runner/work/gate/gate/pkg/edition/java/lite/forward.go:381 +0x66
created by go.minekube.com/gate/pkg/edition/java/lite.resolveStatusResponse in goroutine 81994
        /home/runner/work/gate/gate/pkg/edition/java/lite/forward.go:381 +0x54c


goroutine 81995 [running]:
golang.org/x/sync/singleflight.(*Group).doCall.func1()
        /home/runner/go/pkg/mod/golang.org/x/sync@v0.5.0/singleflight/singleflight.go:170 +0x2b3
golang.org/x/sync/singleflight.(*Group).doCall(0xb33880?, 0xc0000fb590?, {0xc00291e1c0?, 0x19?}, 0xc0026dc180?)
        /home/runner/go/pkg/mod/golang.org/x/sync@v0.5.0/singleflight/singleflight.go:205 +0xb1
golang.org/x/sync/singleflight.(*Group).Do(0xc00010faa0, {0xc00291e1c0, 0x19}, 0xc0003e26b8?)
        /home/runner/go/pkg/mod/golang.org/x/sync@v0.5.0/singleflight/singleflight.go:113 +0x15a
github.com/jellydator/ttlcache/v3.(*SuppressedLoader[...]).Load(0xd35e60, 0xc000142c00, {{0xc001890a98, 0x13}, 0x2fb})
        /home/runner/go/pkg/mod/github.com/jellydator/ttlcache/v3@v3.1.1/cache.go:703 +0x111
github.com/jellydator/ttlcache/v3.(*Cache[...]).getWithOpts(0xd44620, {{0xc001890a98, 0x100000001?}, 0xc000aa3140?}, 0x1?, {0xc0003e27c0, 0x1, 0xc0003e27d0})
        /home/runner/go/pkg/mod/github.com/jellydator/ttlcache/v3@v3.1.1/cache.go:229 +0x236
github.com/jellydator/ttlcache/v3.(*Cache[...]).Get(...)
        /home/runner/go/pkg/mod/github.com/jellydator/ttlcache/v3@v3.1.1/cache.go:321
go.minekube.com/gate/pkg/edition/java/lite.resolveStatusResponse.func3()
        /home/runner/work/gate/gate/pkg/edition/java/lite/forward.go:381 +0x66
created by go.minekube.com/gate/pkg/edition/java/lite.resolveStatusResponse in goroutine 81994
        /home/runner/work/gate/gate/pkg/edition/java/lite/forward.go:381 +0x54c
```

**Comment by robinbraemer** [comment]
fixed by [6e35d73](https://github.com/minekube/gate/commit/6e35d7304b5c64b92b3e036d56e38170f238f628)
